#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : leveldb
Version  : 1.18
Release  : 1
URL      : https://github.com/google/leveldb/archive/v1.18.tar.gz
Source0  : https://github.com/google/leveldb/archive/v1.18.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Patch1: 0112-makefile_install.patch

%description
leveldb: A key-value store
Authors: Sanjay Ghemawat (sanjay@google.com) and Jeff Dean (jeff@google.com)

%package dev
Summary: dev components for the leveldb package.
Group: Development
Provides: leveldb-devel

%description dev
dev components for the leveldb package.


%prep
%setup -q -n leveldb-1.18
%patch1 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/local/lib/libleveldb.so
/usr/local/lib/libleveldb.so.1
/usr/local/lib/libleveldb.so.1.18

%files dev
%defattr(-,root,root,-)
/usr/local/include/leveldb/c.h
/usr/local/include/leveldb/cache.h
/usr/local/include/leveldb/comparator.h
/usr/local/include/leveldb/db.h
/usr/local/include/leveldb/dumpfile.h
/usr/local/include/leveldb/env.h
/usr/local/include/leveldb/filter_policy.h
/usr/local/include/leveldb/iterator.h
/usr/local/include/leveldb/options.h
/usr/local/include/leveldb/slice.h
/usr/local/include/leveldb/status.h
/usr/local/include/leveldb/table.h
/usr/local/include/leveldb/table_builder.h
/usr/local/include/leveldb/write_batch.h
