#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : leveldb
Version  : 1.22
Release  : 9
URL      : https://github.com/google/leveldb/archive/1.22/leveldb-1.22.tar.gz
Source0  : https://github.com/google/leveldb/archive/1.22/leveldb-1.22.tar.gz
Summary  : A fast and lightweight key/value database library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: leveldb-lib = %{version}-%{release}
Requires: leveldb-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev

%description
**LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.**

%package dev
Summary: dev components for the leveldb package.
Group: Development
Requires: leveldb-lib = %{version}-%{release}
Provides: leveldb-devel = %{version}-%{release}
Requires: leveldb = %{version}-%{release}

%description dev
dev components for the leveldb package.


%package lib
Summary: lib components for the leveldb package.
Group: Libraries
Requires: leveldb-license = %{version}-%{release}

%description lib
lib components for the leveldb package.


%package license
Summary: license components for the leveldb package.
Group: Default

%description license
license components for the leveldb package.


%prep
%setup -q -n leveldb-1.22

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556981660
mkdir -p clr-build
pushd clr-build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1556981660
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/leveldb
cp LICENSE %{buildroot}/usr/share/package-licenses/leveldb/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/leveldb/c.h
/usr/include/leveldb/cache.h
/usr/include/leveldb/comparator.h
/usr/include/leveldb/db.h
/usr/include/leveldb/dumpfile.h
/usr/include/leveldb/env.h
/usr/include/leveldb/export.h
/usr/include/leveldb/filter_policy.h
/usr/include/leveldb/iterator.h
/usr/include/leveldb/options.h
/usr/include/leveldb/slice.h
/usr/include/leveldb/status.h
/usr/include/leveldb/table.h
/usr/include/leveldb/table_builder.h
/usr/include/leveldb/write_batch.h
/usr/lib64/cmake/leveldb/leveldbConfig.cmake
/usr/lib64/cmake/leveldb/leveldbConfigVersion.cmake
/usr/lib64/cmake/leveldb/leveldbTargets-relwithdebinfo.cmake
/usr/lib64/cmake/leveldb/leveldbTargets.cmake
/usr/lib64/libleveldb.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libleveldb.so.1
/usr/lib64/libleveldb.so.1.22.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/leveldb/LICENSE
